server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
  port: ${PORT:8080}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:GoldCandy562004}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/talentshift?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:bYfFml3KXwYj6t9uXxTz3KQm1aRP+F0T2r+TfQJzrXc=}

# MoMo Configuration (Sandbox)
momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  api-endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  return-url: ${MOMO_RETURN_URL:https://talentshiftservice.onrender.com/api/momo/return}
  notify-url: ${MOMO_NOTIFY_URL:https://talentshiftservice.onrender.com/api/momo/callback}
  frontend-url: ${MOMO_FRONTEND_URL:http://localhost:5173}

vnpay:
  tmnCode: 6TZBIZ4W
  secretKey: VMBRDFDCQQ2POO8TLNKCRUP6E0E7VHUI
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: ${VNPAY_RETURN_URL:https://talentshiftservice.onrender.com/api/vnpay/return}

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.type.descriptor.sql: warn
    com.zaxxer.hikari: warn
    com.mysql.cj: warn

# File upload configuration
file:
  upload-dir: ${UPLOAD_DIR:/tmp/uploads}